"""Regenerate backend/uv.lock and backend/constraints.lock.txt together.

Two files, one source of truth. `uv.lock` is what `uv` itself reads; this
project's CI and Docker builds use plain `pip`, which cannot read a `uv.lock`
directly, so `constraints.lock.txt` is a flat, `pip -c`-compatible projection
of it (every package pinned to the exact version the lock resolved), kept in
sync by always regenerating both from the same `uv lock` run rather than by
hand-editing either.

`detect-secrets` is deliberately left out of constraints.lock.txt:
.github/workflows/security.yml pins it to an exact, manually-reviewed version
independent of this lock, because the `detect-secrets-hook` treats *any*
version mismatch against `.secrets.baseline` as "needs updating" — bumping it
is its own deliberate step, not something a routine relock should do.

Run this whenever pyproject.toml's dependencies change, or periodically to
pick up patch releases — then run the test suite before committing the
result, the same review any dependency bump gets.

Usage: `python -m scripts.relock` (from `backend/`).
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parent.parent
CONSTRAINTS_PATH = BACKEND_ROOT / "constraints.lock.txt"
EXCLUDED_PACKAGES = {"detect-secrets"}

HEADER = """\
# Generated by `python -m scripts.relock` from uv.lock — do not hand-edit.
# A pip `-c` constraints file: every package pinned to the exact version
# uv's resolver locked, so `pip install -c constraints.lock.txt ...`
# installs the same tree uv.lock describes without requiring pip itself
# to understand uv.lock's format.
#
# detect-secrets is deliberately excluded: .github/workflows/security.yml
# pins it to an exact, manually-reviewed version independent of this lock
# (see that file's own comment for why).
"""

_REQUIREMENT_LINE = re.compile(r"^[A-Za-z0-9_.\-]+==")


def main() -> int:
    subprocess.run(["uv", "lock"], cwd=BACKEND_ROOT, check=True)

    export = subprocess.run(
        [
            "uv",
            "export",
            "--no-hashes",
            "--no-dev",
            "--all-extras",
            "--format",
            "requirements-txt",
        ],
        cwd=BACKEND_ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout

    pinned = []
    for line in export.splitlines():
        stripped = line.strip()
        if not _REQUIREMENT_LINE.match(stripped):
            continue
        name = stripped.split("==", 1)[0].lower()
        if name in EXCLUDED_PACKAGES:
            continue
        pinned.append(stripped)

    pinned.sort(key=str.lower)
    CONSTRAINTS_PATH.write_text(HEADER + "\n".join(pinned) + "\n")
    print(f"wrote {len(pinned)} pinned packages to {CONSTRAINTS_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
